INSERT OVERWRITE TABLE local.gold_zone.KTVH_Do_tin_cay_xuat_tuyen (
    ID_Don_Vi_Quan_Ly,
    ID_May_Cat,
    Ma_May_Cat,
    Ten_May_Cat,
    So_KH,
    Nhom_Ma,
    Nam,
    Thang,
    Tong_so_lan,
    Keo_dai_tong_so_lan,
    Keo_dai_tong_so_lan_xuat_tuyen,
    Keo_dai_tong_so_lan_DZ,
    Thoang_qua_tong_so_lan,
    Thoang_qua_tong_so_lan_xuat_tuyen,
    Thoang_qua_tong_so_lan_DZ,
    MAIFI,
    SAIDI,
    SAIFI,
    CAIDI,
    CAIFI,
    MAIFI_Cong_Ty,
    SAIDI_Cong_Ty,
    SAIFI_Cong_Ty,
    MAIFI_Tong_Cong_Ty,
    SAIDI_Tong_Cong_Ty,
    SAIFI_Tong_Cong_Ty,
    ID_Don_Vi_Quan_ly_Tinh
)
SELECT
    ma_dviqly AS ID_Don_Vi_Quan_Ly,
    CAST(id_mc AS BIGINT) AS ID_May_Cat,
    ma_mc AS Ma_May_Cat,
    ten_mc AS Ten_May_Cat,
    CAST(sokh AS BIGINT) AS So_KH,
    nhomma AS Nhom_Ma,
    CAST(nam AS BIGINT) AS Nam,
    CAST(thang AS BIGINT) AS Thang,
    CAST(tong_sl AS BIGINT) AS Tong_so_lan,
    CAST(keodai_tong_sl AS BIGINT) AS Keo_dai_tong_so_lan,
    CAST(keodai_tong_sl_xt AS BIGINT) AS Keo_dai_tong_so_lan_xuat_tuyen,
    CAST(keodai_tong_sl_dz AS BIGINT) AS Keo_dai_tong_so_lan_DZ,
    CAST(thoangqua_tong_sl AS BIGINT) AS Thoang_qua_tong_so_lan,
    CAST(thoangqua_tong_sl_xt AS BIGINT) AS Thoang_qua_tong_so_lan_xuat_tuyen,
    CAST(thoangqua_tong_sl_dz AS BIGINT) AS Thoang_qua_tong_so_lan_DZ,
    CAST(maifi AS BIGINT) AS MAIFI,
    CAST(saidi AS BIGINT) AS SAIDI,
    CAST(saifi AS BIGINT) AS SAIFI,
    CAST(caidi AS BIGINT) AS CAIDI,
    CAST(caifi AS BIGINT) AS CAIFI,
    CAST(maifi_cty AS BIGINT) AS MAIFI_Cong_Ty,
    CAST(saidi_cty AS BIGINT) AS SAIDI_Cong_Ty,
    CAST(saifi_cty AS BIGINT) AS SAIFI_Cong_Ty,
    CAST(maifi_tcty AS BIGINT) AS MAIFI_Tong_Cong_Ty,
    CAST(saidi_tcty AS BIGINT) AS SAIDI_Tong_Cong_Ty,
    CAST(saifi_tcty AS BIGINT) AS SAIFI_Tong_Cong_Ty,
    CAST(ma_dviqly_tinh AS BIGINT) AS ID_Don_Vi_Quan_ly_Tinh
FROM local.raw_zone.dotincay_xuattuyen
UNION ALL
SELECT
    ma_dviqly AS ID_Don_Vi_Quan_Ly,
    CAST(id_mc AS BIGINT) AS ID_May_Cat,
    ma_mc AS Ma_May_Cat,
    ten_mc AS Ten_May_Cat,
    CAST(sokh AS BIGINT) AS So_KH,
    nhomma AS Nhom_Ma,
    CAST(nam AS BIGINT) AS Nam,
    CAST(thang AS BIGINT) AS Thang,
    CAST(tong_sl AS BIGINT) AS Tong_so_lan,
    CAST(keodai_tong_sl AS BIGINT) AS Keo_dai_tong_so_lan,
    CAST(keodai_tong_sl_xt AS BIGINT) AS Keo_dai_tong_so_lan_xuat_tuyen,
    CAST(keodai_tong_sl_dz AS BIGINT) AS Keo_dai_tong_so_lan_DZ,
    CAST(thoangqua_tong_sl AS BIGINT) AS Thoang_qua_tong_so_lan,
    CAST(thoangqua_tong_sl_xt AS BIGINT) AS Thoang_qua_tong_so_lan_xuat_tuyen,
    CAST(thoangqua_tong_sl_dz AS BIGINT) AS Thoang_qua_tong_so_lan_DZ,
    CAST(maifi AS BIGINT) AS MAIFI,
    CAST(saidi AS BIGINT) AS SAIDI,
    CAST(saifi AS BIGINT) AS SAIFI,
    CAST(caidi AS BIGINT) AS CAIDI,
    CAST(caifi AS BIGINT) AS CAIFI,
    CAST(maifi_cty AS BIGINT) AS MAIFI_Cong_Ty,
    CAST(saidi_cty AS BIGINT) AS SAIDI_Cong_Ty,
    CAST(saifi_cty AS BIGINT) AS SAIFI_Cong_Ty,
    CAST(maifi_tcty AS BIGINT) AS MAIFI_Tong_Cong_Ty,
    CAST(saidi_tcty AS BIGINT) AS SAIDI_Tong_Cong_Ty,
    CAST(saifi_tcty AS BIGINT) AS SAIFI_Tong_Cong_Ty,
    CAST(ma_dviqly_tinh AS BIGINT) AS ID_Don_Vi_Quan_ly_Tinh
FROM local.raw_zone.dotincay_kehoach_xuattuyen;